# Dott Configuration Example - Logo Type in Structure Build
# This example demonstrates specifying logo type directly in structure.build

# Structure defines the layout and order of modules
[structure]
position = "center"

[[structure.build]]
module = "logo:default"   # Logo type specified here (can be "logo:default", "logo:custom", or "logo:image")

[[structure.build]]
module = "break"

[[structure.build]]
module = "entries"

[[structure.build]]
module = "break"

[[structure.build]]
module = "help"

# Entries - terminal commands with name, command, and arguments
[[entries]]
name = "View Dotfiles"
command = "yazi"
args = ["~/.config"]

[[entries]]
name = "Edit Dott Config"
command = ""
args = []

[[entries]]
name = "View Shell"
command = ""
args = []

[[entries]]
name = "Quit"
command = ""
args = []

# Custom modules configuration
[custom]

# Terminal colors module - displays color palette
[custom.terminal_colors]
shape = "circles"

# Clock module - displays current time
[custom.clock]

# Configure break to add custom number of empty lines
[custom.break]
lines = 3  # Each break adds 3 empty lines instead of default 2
