# Dott Configuration Example with Terminal Colors (Squares) and Clock
# This file demonstrates the optional modules with alternate configurations

# Logo type: "default" or "custom"
logo_type = "default"

# Menu items - each item can have a name, command, and arguments
[[menu_items]]
name = "View Dotfiles"
command = "yazi"
args = ["~/.config"]

[[menu_items]]
name = "Edit Dott Config"
command = ""
args = []

[[menu_items]]
name = "View Shell"
command = ""
args = []

[[menu_items]]
name = "Quit"
command = ""
args = []

# Terminal colors module with square grid (2 rows, 4 entries each)
# The colors are displayed below the menu items.
[terminal_colors]
shape = "squares"

# Clock module - displayed directly under the keybindings
# The position field is kept for backwards compatibility but is ignored.
[clock]
position = "top"
