# Comprehensive Dott Configuration Example
# Demonstrates all features including multiple entry clusters

# Logo type can be set here for backward compatibility
# But can also be specified in structure.build as "logo:default", "logo:custom", or "logo:image"
logo_type = "default"

[structure]
position = "center"

[structure.build]
1 = "logo"          # Can also be "logo:default", "logo:custom", or "logo:image"
2 = "break"
3 = "clock"
4 = "break"
5 = "entries"
6 = "break"
7 = "entries2"
8 = "break"
9 = "entries3"
10 = "break"
11 = "colors"
12 = "break"
13 = "help"

# Development tools
[[entries]]
name = "Edit Neovim"
command = "nvim"
args = ["~/.config/nvim/init.lua"]

[[entries]]
name = "Edit Dott"
command = "nvim"
args = ["~/.config/dott/config.toml"]

# File management
[[entries2]]
name = "Browse Config"
command = "yazi"
args = ["~/.config"]

[[entries2]]
name = "Browse Home"
command = "yazi"
args = ["~"]

# System tools
[[entries3]]
name = "System Monitor"
command = "htop"
args = []

[[entries3]]
name = "Git Status"
command = "lazygit"
args = []

[[entries3]]
name = "Quit"
command = ""
args = []

[custom]

[custom.terminal_colors]
shape = "circles"

[custom.clock]

# Configure break to skip 2 lines (default)
# You can change this to any number
[custom.break]
lines = 2
