# Dott Configuration Example with Terminal Colors and Clock Modules
# This file demonstrates the optional terminal colors and clock modules

# Logo type: "default" or "custom"
logo_type = "default"

# Menu items - each item can have a name, command, and arguments
[[menu_items]]
name = "View Dotfiles"
command = "yazi"
args = ["~/.config"]

[[menu_items]]
name = "Edit Dott Config"
command = ""
args = []

[[menu_items]]
name = "View Shell"
command = ""
args = []

[[menu_items]]
name = "Quit"
command = ""
args = []

# Terminal colors module (optional)
# shape can be "circles" or "squares"
# - circles: 1 row of 8 color entries
# - squares: 2 rows with 4 horizontal entries
[terminal_colors]
shape = "circles"

# Clock module (optional)
# position can be "top" or "bottom"
# - top: below the logo, before modules start
# - bottom: above the help text
[clock]
position = "bottom"
